remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: SimpleCodez
description: Simple Code / Smart Apps
exclude:
  - .DS_Store
  - .gitignore
  - .sass-cache
  - .github
  - _site
  - Gemfile
  - Gemfile.lock
  - AGENTS.md
markdown: kramdown
